/* Cloud Songs - language catalogue.
 *
 * Built from JioSaavn's featured-playlists endpoint, which keys language
 * off an 'L' cookie (the ?language= query param is ignored and returns
 * identical results for every language).
 *
 *   latest    - the newest/chart list for that language; loaded as soon
 *               as the language is selected.
 *   playlists - the rest, shown as cards on the main page.
 *
 * Every 'latest' entry was verified to resolve through /playlist/ with
 * all tracks streamable. Regenerate if these go stale.
 */
window.SAAVN_LANGS = [
	{ code: "hindi", label: "Hindi",
	  latest: { name: "Taaza Tunes", url: "https://www.jiosaavn.com/featured/taaza-tunes/Me5RridRfDk_", img: "https://c.saavncdn.com/editorial/TaazaTunes_20260904120006.jpg", n: "50" },
	  playlists: [
		{ name: "Happy Teacher's Day", url: "https://www.jiosaavn.com/featured/happy-teachers-day/4goffGVmucFuOxiEGmm6lQ__", img: "https://c.saavncdn.com/editorial/HappyTeacher_sDay_20260904053744.jpg", n: "20" },
		{ name: "Go Go Govinda", url: "https://www.jiosaavn.com/featured/go-go-govinda/K-3jHN5oflfc1EngHtQQ2g__", img: "https://c.saavncdn.com/editorial/GoGoGovinda_20260902063102.jpg", n: "21" },
		{ name: "Viral Nation", url: "https://www.jiosaavn.com/featured/viral-nation/tfVkYjaAbZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ViralNation_20260831114743.jpg", n: "30" },
		{ name: "Let's Play - Rishi Kapoor", url: "https://www.jiosaavn.com/featured/lets-play-rishi-kapoor/pFknS49CYag_", img: "https://c.saavncdn.com/editorial/Let_sPlayRishiKapoor_20240229050222.jpg", n: "25" },
		{ name: "Romantic Hits 2026 - Hindi", url: "https://www.jiosaavn.com/featured/romantic-hits-2026-hindi/GIPBPar27Cbwf4TNfa3cig__", img: "https://c.saavncdn.com/editorial/RomanticHits2026Hindi_20260707083404.jpg", n: "20" },
		{ name: "ArtistOne Finds", url: "https://www.jiosaavn.com/featured/artistone-finds/nOyNH0fuWtGP3AiNrzXpzA__", img: "https://c.saavncdn.com/editorial/ArtistOneFinds_20260904103023.jpg", n: "50" },
		{ name: "Hindi Hit Songs", url: "https://www.jiosaavn.com/featured/hindi-hit-songs/ZodsPn39CSjwxP8tCU-flw__", img: "https://c.saavncdn.com/editorial/HindiHitSongs_20260902093325.jpg", n: "25" },
		{ name: "Dance Hits 2026 - Hindi", url: "https://www.jiosaavn.com/featured/dance-hits-2026-hindi/1Osn,A1PoiVwl9Cu-HDmVQ__", img: "https://c.saavncdn.com/editorial/DanceHits2026Hindi_20260706105740.jpg", n: "20" },
		{ name: "Best Of Pop - Hindi", url: "https://www.jiosaavn.com/featured/best-of-pop-hindi/xHa-oM3ldXAwkg5tVhI3fw__", img: "https://c.saavncdn.com/editorial/BestOfPopHindi_20260824093258.jpg", n: "50" },
		{ name: "Best Of 90s - Hindi", url: "https://www.jiosaavn.com/featured/best-of-90s-hindi/j44dgfQrkXY_", img: "https://c.saavncdn.com/editorial/BestOf90sHindi_20251125041813.jpg", n: "50" },
	] },
	{ code: "english", label: "English",
	  latest: { name: "Fresh Rock Hits - English", url: "https://www.jiosaavn.com/featured/fresh-rock-hits-english/LlG94Or10VVuOxiEGmm6lQ__", img: "https://c.saavncdn.com/editorial/FreshRockHitsEnglish_20260710120114.jpg", n: "50" },
	  playlists: [
		{ name: "Chartbusters 2026 - International", url: "https://www.jiosaavn.com/featured/chartbusters-2026-international/ck-nuL,boLnuS6o99JG3mQ__", img: "https://c.saavncdn.com/editorial/Chartbusters2026International_20260707100417.jpg", n: "50" },
		{ name: "Teachers Day Special", url: "https://www.jiosaavn.com/featured/teachers-day-special/wljG9o2P9oAGSw2I1RxdhQ__", img: "https://c.saavncdn.com/editorial/TeachersDaySpecial_20260904125827.jpg", n: "25" },
		{ name: "Viral Nation", url: "https://www.jiosaavn.com/featured/viral-nation/tfVkYjaAbZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ViralNation_20260831114743.jpg", n: "30" },
		{ name: "Fresh Dance Hits", url: "https://www.jiosaavn.com/featured/fresh-dance-hits/rEDxb7swgvE_", img: "https://c.saavncdn.com/editorial/FreshDanceHits_20260904124812.jpg", n: "30" },
		{ name: "Feel Good Pop", url: "https://www.jiosaavn.com/featured/feel-good-pop/Er9SBlcxDtZFo9wdEAzFBA__", img: "https://c.saavncdn.com/editorial/FeelGoodPop_20260623120341.jpg", n: "50" },
		{ name: "ArtistOne Finds", url: "https://www.jiosaavn.com/featured/artistone-finds/nOyNH0fuWtGP3AiNrzXpzA__", img: "https://c.saavncdn.com/editorial/ArtistOneFinds_20260904103023.jpg", n: "50" },
		{ name: "Rock Workout", url: "https://www.jiosaavn.com/featured/rock-workout/c5VsX4cw-EnuCJW60TJk1Q__", img: "https://c.saavncdn.com/editorial/RockWorkout_20260722124716.jpg", n: "50" },
		{ name: "K-Pop Dance Hits", url: "https://www.jiosaavn.com/featured/k-pop-dance-hits/nu8lkO4o-inufxkxMEIbIw__", img: "https://c.saavncdn.com/editorial/KPopDanceHits_20251223110629.jpg", n: "50" },
		{ name: "Drive Time Hip Hop", url: "https://www.jiosaavn.com/featured/drive-time-hip-hop/-WeiPOsIS0oGSw2I1RxdhQ__", img: "https://c.saavncdn.com/editorial/DriveTimeHipHop_20260722130245.jpg", n: "45" },
		{ name: "Chill Beats", url: "https://www.jiosaavn.com/featured/chill-beats/suCVEatbqVBuOxiEGmm6lQ__", img: "https://c.saavncdn.com/editorial/ChillBeats_20260414110016.jpg", n: "30" },
	] },
	{ code: "punjabi", label: "Punjabi",
	  latest: { name: "Chartbusters 2025 - Punjabi", url: "https://www.jiosaavn.com/featured/chartbusters-2025-punjabi/2AH33eZMm6KtaPBmwNDuaA__", img: "https://c.saavncdn.com/editorial/Chartbusters2025Punjabi_20260109053524.jpg", n: "50" },
	  playlists: [
		{ name: "Hip Hop Hits 2026 - Punjabi", url: "https://www.jiosaavn.com/featured/hip-hop-hits-2026-punjabi/KQAjYS4PW73WCn-BpjaL7g__", img: "https://c.saavncdn.com/editorial/HipHopHits2026Punjabi_20260707081504.jpg", n: "20" },
		{ name: "Let's Play - Diljit Dosanjh - Punjabi", url: "https://www.jiosaavn.com/featured/lets-play-diljit-dosanjh-punjabi/0kQshFJLbtQ_", img: "https://c.saavncdn.com/editorial/Let_sPlayDiljitDosanjhPunjabi_20240807075958.jpg", n: "50" },
		{ name: "Viral Nation", url: "https://www.jiosaavn.com/featured/viral-nation/tfVkYjaAbZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ViralNation_20260831114743.jpg", n: "30" },
		{ name: "Romantic Duets - Punjabi", url: "https://www.jiosaavn.com/featured/romantic-duets-punjabi/T0SjV7ntUk3uCJW60TJk1Q__", img: "https://c.saavncdn.com/editorial/RomanticDuetsPunjabi_20260821083349.jpg", n: "50" },
		{ name: "Let's Play - Guru Randhawa - Punjabi", url: "https://www.jiosaavn.com/featured/lets-play-guru-randhawa-punjabi/94YhtIvnV08_", img: "https://c.saavncdn.com/editorial/Let_sPlayGuruRandhawaPunjabi_20250919080924.jpg", n: "50" },
		{ name: "ArtistOne Finds", url: "https://www.jiosaavn.com/featured/artistone-finds/nOyNH0fuWtGP3AiNrzXpzA__", img: "https://c.saavncdn.com/editorial/ArtistOneFinds_20260904103023.jpg", n: "50" },
		{ name: "Best of Sad Romantic - Punjabi", url: "https://www.jiosaavn.com/featured/best-of-sad-romantic-punjabi/ql-Fy0XF8STufxkxMEIbIw__", img: "https://c.saavncdn.com/editorial/BestofSadRomanticPunjabi_20251124094133.jpg", n: "45" },
		{ name: "Let's Play - Neha Kakkar - Punjabi", url: "https://www.jiosaavn.com/featured/lets-play-neha-kakkar-punjabi/lAlrJRH8FME_", img: "https://c.saavncdn.com/editorial/Let_sPlayNehaKakkarPunjabi_20250311150805.jpg", n: "36" },
		{ name: "Barsaat Te Dance", url: "https://www.jiosaavn.com/featured/barsaat-te-dance/GO2Zil-iYexFo9wdEAzFBA__", img: "https://c.saavncdn.com/editorial/BarsaatTeDance_20260708073507.jpg", n: "26" },
		{ name: "Best of Indie - Punjabi", url: "https://www.jiosaavn.com/featured/best-of-indie-punjabi/9f-F4X-0-7jc1EngHtQQ2g__", img: "https://c.saavncdn.com/editorial/BestofIndiePunjabi_20241025070354.jpg", n: "30" },
	] },
	{ code: "tamil", label: "Tamil",
	  latest: { name: "Chartbusters 2026 - Tamil", url: "https://www.jiosaavn.com/featured/chartbusters-2026-tamil/t8YKA39g1ft5b0dfvYvasw__", img: "https://c.saavncdn.com/editorial/Chartbusters2026Tamil_20260708050856.jpg", n: "50" },
	  playlists: [
		{ name: "Dance Queens - Tamil", url: "https://www.jiosaavn.com/featured/dance-queens-tamil/2uwAUQjOVlnfemJ68FuXsA__", img: "https://c.saavncdn.com/editorial/DanceQueensTamil_20260825130211.jpg", n: "30" },
		{ name: "Let's Play - Vijay", url: "https://www.jiosaavn.com/featured/lets-play-vijay/-KAZYpBulyM_", img: "https://c.saavncdn.com/editorial/Let_sPlayVijay_20250217095544.jpg", n: "50" },
		{ name: "Viral Nation", url: "https://www.jiosaavn.com/featured/viral-nation/tfVkYjaAbZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ViralNation_20260831114743.jpg", n: "30" },
		{ name: "Therific Theme", url: "https://www.jiosaavn.com/featured/therific-theme/,JL,xvmQHE0_", img: "https://c.saavncdn.com/editorial/TherificTheme_20260624052234.jpg", n: "50" },
		{ name: "Thaai Manne Vanakkam", url: "https://www.jiosaavn.com/featured/thaai-manne-vanakkam/49KtR2M1IXVuOxiEGmm6lQ__", img: "https://c.saavncdn.com/editorial/ThaaiManneVanakkam_20260112062438.jpg", n: "26" },
		{ name: "ArtistOne Finds", url: "https://www.jiosaavn.com/featured/artistone-finds/nOyNH0fuWtGP3AiNrzXpzA__", img: "https://c.saavncdn.com/editorial/ArtistOneFinds_20260904103023.jpg", n: "50" },
		{ name: "Tamil BGM", url: "https://www.jiosaavn.com/featured/tamil-bgm/Ces,YrZsy4c14faDlWgB3A__", img: "https://c.saavncdn.com/editorial/TamilBGM_20260811075813.jpg", n: "42" },
		{ name: "Top Kuthu - Tamil", url: "https://www.jiosaavn.com/featured/top-kuthu-tamil/CNVzQf7lvT8wkg5tVhI3fw__", img: "https://c.saavncdn.com/editorial/TopKuthuTamil_20260617060004.jpg", n: "40" },
		{ name: "Let's Play - Anirudh Ravichander - Tamil", url: "https://www.jiosaavn.com/featured/lets-play-anirudh-ravichander-tamil/ePUVUJs1h,E_", img: "https://c.saavncdn.com/editorial/Let_sPlayAnirudhRavichanderTamil_20250217095503.jpg", n: "50" },
		{ name: "Let's Play - Rajinikanth", url: "https://www.jiosaavn.com/featured/lets-play-rajinikanth/hVwUe6exUYM_", img: "https://c.saavncdn.com/editorial/Let_sPlayRajinikanth_20250218065230.jpg", n: "50" },
	] },
	{ code: "telugu", label: "Telugu",
	  latest: { name: "Chartbusters 2026 - Telugu", url: "https://www.jiosaavn.com/featured/chartbusters-2026-telugu-/-HLoFb-L3r2sud-ETNX4vg__", img: "https://c.saavncdn.com/editorial/Chartbusters2026SoFarTelugu_20260709092335.jpg", n: "50" },
	  playlists: [
		{ name: "Let's Play - Nani - Telugu", url: "https://www.jiosaavn.com/featured/lets-play-nani-telugu/bV-AtS0lEsQ_", img: "https://c.saavncdn.com/editorial/Let_sPlayNaniTelugu_20250217162110.jpg", n: "50" },
		{ name: "Weekend Masala", url: "https://www.jiosaavn.com/featured/weekend-masala/04y9CRp2ht1ieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/WeekendMasala_20251128125426.jpg", n: "50" },
		{ name: "Viral Nation", url: "https://www.jiosaavn.com/featured/viral-nation/tfVkYjaAbZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ViralNation_20260831114743.jpg", n: "30" },
		{ name: "Chartbusters 2026 - Telugu", url: "https://www.jiosaavn.com/featured/chartbusters-2026-telugu-/-HLoFb-L3r2sud-ETNX4vg__", img: "https://c.saavncdn.com/editorial/Chartbusters2026SoFarTelugu_20260709092335.jpg", n: "50" },
		{ name: "Let's Play - Sid Sriram - Telugu", url: "https://www.jiosaavn.com/featured/lets-play-sid-sriram-telugu/JPy8PzDyxH6O0eMLZZxqsA__", img: "https://c.saavncdn.com/editorial/Let_sPlaySidSriramTelugu_20241218070925.jpg", n: "50" },
		{ name: "ArtistOne Finds", url: "https://www.jiosaavn.com/featured/artistone-finds/nOyNH0fuWtGP3AiNrzXpzA__", img: "https://c.saavncdn.com/editorial/ArtistOneFinds_20260904103023.jpg", n: "50" },
		{ name: "Best of 2000s  - Telugu", url: "https://www.jiosaavn.com/featured/best-of-2000s-telugu/bQMyMLNStspieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/Bestof2000sTelugu_20260623102320.jpg", n: "50" },
		{ name: "Best Of Indie - Telugu", url: "https://www.jiosaavn.com/featured/best-of-indie-telugu/9mgN8,ozuvyO0eMLZZxqsA__", img: "https://c.saavncdn.com/editorial/BestOfIndieTelugu_20260807124813.jpg", n: "29" },
		{ name: "Let's Play - Ravi Teja - Telugu", url: "https://www.jiosaavn.com/featured/lets-play-ravi-teja-telugu/EZ9UMLcs1M8_", img: "https://c.saavncdn.com/editorial/Let_sPlayRaviTejaTelugu_20231222075126.jpg", n: "50" },
		{ name: "Telugu Folk Songs", url: "https://www.jiosaavn.com/featured/telugu-folk-songs/AEp,YEFQXKdFo9wdEAzFBA__", img: "https://c.saavncdn.com/editorial/TeluguFolkSongs_20260623104212.jpg", n: "50" },
	] },
	{ code: "marathi", label: "Marathi",
	  latest: { name: "Chartbusters 2026 - Marathi", url: "https://www.jiosaavn.com/featured/chartbusters-2026-marathi/Hl69FQZsAorwxP8tCU-flw__", img: "https://c.saavncdn.com/editorial/Chartbusters2026Marathi_20260709130019.jpg", n: "50" },
	  playlists: [
		{ name: "Let's Play - Sanju Rathod - Marathi", url: "https://www.jiosaavn.com/featured/lets-play-sanju-rathod-marathi/gjdPYxUSfOP5me0dITeP4w__", img: "https://c.saavncdn.com/editorial/Let_sPlaySanjuRathodMarathi_20260107072255.jpg", n: "33" },
		{ name: "Weekend Misal", url: "https://www.jiosaavn.com/featured/weekend-misal/vLIwrLpKA37femJ68FuXsA__", img: "https://c.saavncdn.com/editorial/WeekendMisal_20260618111612.jpg", n: "38" },
		{ name: "Viral Nation", url: "https://www.jiosaavn.com/featured/viral-nation/tfVkYjaAbZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ViralNation_20260831114743.jpg", n: "30" },
		{ name: "Romantic Hits 2026 - Marathi", url: "https://www.jiosaavn.com/featured/romantic-hits-2026-marathi/NTgZRwAKls,Tb7czG7lKZg__", img: "https://c.saavncdn.com/editorial/RomanticHits2026Marathi_20260709130830.jpg", n: "20" },
		{ name: "Marathi Pop Romance", url: "https://www.jiosaavn.com/featured/marathi-pop-romance/oiMTAuV9oISO0eMLZZxqsA__", img: "https://c.saavncdn.com/editorial/MarathiPopRomance_20260703140250.jpg", n: "36" },
		{ name: "ArtistOne Finds", url: "https://www.jiosaavn.com/featured/artistone-finds/nOyNH0fuWtGP3AiNrzXpzA__", img: "https://c.saavncdn.com/editorial/ArtistOneFinds_20260904103023.jpg", n: "50" },
		{ name: "Let's Play - Ajay-Atul - Marathi", url: "https://www.jiosaavn.com/featured/lets-play-ajay-atul-marathi/JuaHJ-qQnu4_", img: "https://c.saavncdn.com/editorial/Let_sPlayAjayAtulMarathi_20251121063159.jpg", n: "50" },
		{ name: "Best of Indie - Marathi", url: "https://www.jiosaavn.com/featured/best-of-indie-marathi/iG6tKoqUI,juCJW60TJk1Q__", img: "https://c.saavncdn.com/editorial/BestofIndieMarathi_20260828114813.jpg", n: "30" },
		{ name: "Chaha Mitra Mandal", url: "https://www.jiosaavn.com/featured/chaha-mitra-mandal/9mmPVL-D1C1ieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ChahaMitraMandal_20251203052817.jpg", n: "23" },
		{ name: "DJ Mix - Marathi", url: "https://www.jiosaavn.com/featured/dj-mix-marathi/k2ITjlhAtKluOxiEGmm6lQ__", img: "https://c.saavncdn.com/editorial/DJMixMarathi_20251202053902.jpg", n: "43" },
	] },
	{ code: "gujarati", label: "Gujarati",
	  latest: { name: "Chartbusters 2024 - Gujarati", url: "https://www.jiosaavn.com/featured/chartbusters-2024-gujarati/1YZhQJT4sT28m7pOZz2ziw__", img: "https://c.saavncdn.com/editorial/Chartbusters2024Gujarati_20241205035023.jpg", n: "39" },
	  playlists: [
		{ name: "Navi Tunes", url: "https://www.jiosaavn.com/featured/navi-tunes/ubQSKC8G63KQBCMgztuf8A__", img: "https://c.saavncdn.com/editorial/NaviTunes_20260831110309.jpg", n: "48" },
		{ name: "Best of Romance - Gujarati", url: "https://www.jiosaavn.com/featured/best-of-romance-gujarati/RTqxx9kuN5T9wIHXZ0JrGQ__", img: "https://c.saavncdn.com/editorial/BestofRomanceGujarati_20250812053922.jpg", n: "33" },
		{ name: "Viral Nation", url: "https://www.jiosaavn.com/featured/viral-nation/tfVkYjaAbZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ViralNation_20260831114743.jpg", n: "30" },
		{ name: "Best of Gaurang Vyas", url: "https://www.jiosaavn.com/featured/best-of-gaurang-vyas/rx6kPvSzIPM_", img: "https://c.saavncdn.com/editorial/logo/BestofGaurangVyas_90234540_20161123.jpg", n: "21" },
		{ name: "Hare Krishna", url: "https://www.jiosaavn.com/featured/hare-krishna/ApTa0bDdfsE_", img: "https://c.saavncdn.com/editorial/KrishnaJanmashtamiGujarati_20260903110534.jpg", n: "44" },
		{ name: "ArtistOne Finds", url: "https://www.jiosaavn.com/featured/artistone-finds/nOyNH0fuWtGP3AiNrzXpzA__", img: "https://c.saavncdn.com/editorial/ArtistOneFinds_20260904103023.jpg", n: "50" },
		{ name: "Shreenathji Ne Arpan", url: "https://www.jiosaavn.com/featured/shreenathji-ne-arpan/Pejt,U085Es_", img: "https://c.saavncdn.com/u/ShreenathjiNeArpan.jpg", n: "22" },
		{ name: "Shrinathji Ni Jhankhi", url: "https://www.jiosaavn.com/featured/shrinathji-ni-jhankhi/P8bvjpLjq0A_", img: "https://c.saavncdn.com/editorial/logo/ShreenathNiJhankhi_20210813050752.jpg", n: "15" },
		{ name: "Dhollywood Chartbusters", url: "https://www.jiosaavn.com/featured/dhollywood-chartbusters/YGmrD7TjFujufxkxMEIbIw__", img: "https://c.saavncdn.com/editorial/DhollywoodChartbusters_20260813070520.jpg", n: "28" },
		{ name: "Shiv - Gujarati", url: "https://www.jiosaavn.com/featured/shiv-gujarati-/ZeiEVEUgOVc_", img: "https://c.saavncdn.com/editorial/OmNamahShivayGujaratiShivBhajans_20250428110246.jpg", n: "39" },
	] },
	{ code: "bengali", label: "Bengali",
	  latest: { name: "Chartbusters 2026 - Bengali", url: "https://www.jiosaavn.com/featured/chartbusters-2026-bengali/WiaQFJLxQfBBMalTlcv5jA__", img: "https://c.saavncdn.com/editorial/Chartbusters2026Bengali_20260707105530.jpg", n: "50" },
	  playlists: [
		{ name: "Let's Play -  Uttam Kumar", url: "https://www.jiosaavn.com/featured/lets-play-uttam-kumar/CuCksWNU89s_", img: "https://c.saavncdn.com/editorial/Let_sPlayUttamKumar_20240621121546.jpg", n: "48" },
		{ name: "Chartbusters 2026 - Bengali", url: "https://www.jiosaavn.com/featured/chartbusters-2026-bengali/WiaQFJLxQfBBMalTlcv5jA__", img: "https://c.saavncdn.com/editorial/Chartbusters2026Bengali_20260707105530.jpg", n: "50" },
		{ name: "Viral Nation", url: "https://www.jiosaavn.com/featured/viral-nation/tfVkYjaAbZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ViralNation_20260831114743.jpg", n: "30" },
		{ name: "Notun Folk", url: "https://www.jiosaavn.com/featured/notun-folk/kub3lfivvABYufGtEEFmDA__", img: "https://c.saavncdn.com/editorial/NotunFolk_20260831114541.jpg", n: "40" },
		{ name: "Romantic Hits 2026 - Bengali", url: "https://www.jiosaavn.com/featured/romantic-hits-2026-bengali/UsEGYJnW5iLwxP8tCU-flw__", img: "https://c.saavncdn.com/editorial/RomanticHits2026Bengali_20260709174224.jpg", n: "20" },
		{ name: "ArtistOne Finds", url: "https://www.jiosaavn.com/featured/artistone-finds/nOyNH0fuWtGP3AiNrzXpzA__", img: "https://c.saavncdn.com/editorial/ArtistOneFinds_20260904103023.jpg", n: "50" },
		{ name: "Let's Play - Lata Mangeshkar - Bengali", url: "https://www.jiosaavn.com/featured/lets-play-lata-mangeshkar-bengali/HB1svgSQIFHuCJW60TJk1Q__", img: "https://c.saavncdn.com/editorial/Let_sPlayLataMangeshkarBengali_20250312093729.jpg", n: "50" },
		{ name: "Best of  80s - Bengali", url: "https://www.jiosaavn.com/featured/best-of-80s-bengali/QogRFghbDMvufxkxMEIbIw__", img: "https://c.saavncdn.com/editorial/Bestof80sBengali_20260810115708.jpg", n: "47" },
		{ name: "Arijit Singh - Love Songs - Bengali", url: "https://www.jiosaavn.com/featured/arijit-singh-love-songs-bengali/Tpi7AUqAq8luOxiEGmm6lQ__", img: "https://c.saavncdn.com/editorial/ArijitSinghLoveSongsBengali_20250110141238.jpg", n: "36" },
		{ name: "Best of Baul - Bengali", url: "https://www.jiosaavn.com/featured/best-of-baul-bengali/EdkZvFAOBda7W4jEHubaRQ__", img: "https://c.saavncdn.com/editorial/BestofBaulBengali_20260410133925.jpg", n: "35" },
	] },
	{ code: "kannada", label: "Kannada",
	  latest: { name: "Chartbusters 2026 - Kannada", url: "https://www.jiosaavn.com/featured/chartbusters-2026-kannada/3hz-57VvANmqKl4yv5iIvA__", img: "https://c.saavncdn.com/editorial/Chartbusters2026Kannada_20260707071646.jpg", n: "50" },
	  playlists: [
		{ name: "Let's Play - Sudeep", url: "https://www.jiosaavn.com/featured/lets-play-sudeep/U5dzC9gz2Gg_", img: "https://c.saavncdn.com/editorial/Let_sPlaySudeep_20240222112309.jpg", n: "55" },
		{ name: "2010s Soulful - Kannada", url: "https://www.jiosaavn.com/featured/2010s-soulful-kannada/AVOZPOyAfpXuCJW60TJk1Q__", img: "https://c.saavncdn.com/editorial/2010sRomanceKannada_20240917104653.jpg", n: "55" },
		{ name: "Viral Nation", url: "https://www.jiosaavn.com/featured/viral-nation/tfVkYjaAbZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ViralNation_20260831114743.jpg", n: "30" },
		{ name: "Yash Love Songs", url: "https://www.jiosaavn.com/featured/yash-love-songs/F28ZGExI4ZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/YashLoveSongs_20240304062334.jpg", n: "21" },
		{ name: "Retro Romance 80s", url: "https://www.jiosaavn.com/featured/retro-romance-80s/2lwe7LLSNgZuOxiEGmm6lQ__", img: "https://c.saavncdn.com/editorial/RetroRomance80s_20250602094900.jpg", n: "45" },
		{ name: "ArtistOne Finds", url: "https://www.jiosaavn.com/featured/artistone-finds/nOyNH0fuWtGP3AiNrzXpzA__", img: "https://c.saavncdn.com/editorial/ArtistOneFinds_20260904103023.jpg", n: "50" },
		{ name: "Top Dance Hits - Kannada", url: "https://www.jiosaavn.com/featured/top-dance-hits-kannada/I,fjnhLsNmgwkg5tVhI3fw__", img: "https://c.saavncdn.com/editorial/TopDanceHitsKannada_20260407113240.jpg", n: "55" },
		{ name: "Rajan  Nagendra Love Songs", url: "https://www.jiosaavn.com/featured/rajan-nagendra-love-songs/NLllm5JVRY3uCJW60TJk1Q__", img: "https://c.saavncdn.com/editorial/RajanNagendra_20250203124009.jpg", n: "55" },
		{ name: "Let's Play - Rahul Dit-o", url: "https://www.jiosaavn.com/featured/lets-play-rahul-dit-o/6peZaoB4HpfufxkxMEIbIw__", img: "https://c.saavncdn.com/editorial/Let_sPlayRahulDito_20240111172333.jpg", n: "38" },
		{ name: "Best Of Indie - Kannada", url: "https://www.jiosaavn.com/featured/best-of-indie-kannada/zxV7U3q91NpieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/BestOfIndieKannada_20260901101608.jpg", n: "30" },
	] },
	{ code: "malayalam", label: "Malayalam",
	  latest: { name: "Chartbusters 2026 - Malayalam", url: "https://www.jiosaavn.com/featured/chartbusters-2026-malayalam/gWOhDiJRymXhCuZvyzI2qg__", img: "https://c.saavncdn.com/editorial/Chartbusters2026Malayalam_20260706072957.jpg", n: "50" },
	  playlists: [
		{ name: "Let's Play - Dulquer Salmaan - Malayalam", url: "https://www.jiosaavn.com/featured/lets-play-dulquer-salmaan-malayalam/FtRINUMZKto_", img: "https://c.saavncdn.com/editorial/Let_sPlayDulquerSalmaan_20240919131307.jpg", n: "41" },
		{ name: "Weekend Sadhya", url: "https://www.jiosaavn.com/featured/weekend-sadhya/Kl3SldGMVC5uOxiEGmm6lQ__", img: "https://c.saavncdn.com/editorial/WeekendSadhya_20260828101457.jpg", n: "43" },
		{ name: "Viral Nation", url: "https://www.jiosaavn.com/featured/viral-nation/tfVkYjaAbZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ViralNation_20260831114743.jpg", n: "30" },
		{ name: "Chartbusters 2026 - Malayalam", url: "https://www.jiosaavn.com/featured/chartbusters-2026-malayalam/gWOhDiJRymXhCuZvyzI2qg__", img: "https://c.saavncdn.com/editorial/Chartbusters2026Malayalam_20260706072957.jpg", n: "50" },
		{ name: "Malayalam Pop Romance", url: "https://www.jiosaavn.com/featured/malayalam-pop-romance/JVZfr2uT4wQwkg5tVhI3fw__", img: "https://c.saavncdn.com/editorial/MalayalamPopRomance_20260817103108.jpg", n: "33" },
		{ name: "ArtistOne Finds", url: "https://www.jiosaavn.com/featured/artistone-finds/nOyNH0fuWtGP3AiNrzXpzA__", img: "https://c.saavncdn.com/editorial/ArtistOneFinds_20260904103023.jpg", n: "50" },
		{ name: "Let's Play - Sid Sriram - Malayalam", url: "https://www.jiosaavn.com/featured/lets-play-sid-sriram-malayalam/V2VrNKZnTQzufxkxMEIbIw__", img: "https://c.saavncdn.com/editorial/Let_sPlaySidSriramMalayalam_20240702120838.jpg", n: "24" },
		{ name: "Let's Play - Nivin Pauly - Malayalam", url: "https://www.jiosaavn.com/featured/lets-play-nivin-pauly-malayalam/XJ4lq3D7vNI_", img: "https://c.saavncdn.com/editorial/Let_sPlayNivinPaulyMalayalam_20241007114443.jpg", n: "50" },
		{ name: "Best of Indie - Malayalam", url: "https://www.jiosaavn.com/featured/best-of-indie-malayalam/TPzO5IY-SwHc1EngHtQQ2g__", img: "https://c.saavncdn.com/editorial/BestofIndieMalayalam_20260831091840.jpg", n: "31" },
		{ name: "Best of Retro - Malayalam", url: "https://www.jiosaavn.com/featured/best-of-retro-malayalam/ogl8p7wBsOduOxiEGmm6lQ__", img: "https://c.saavncdn.com/editorial/BestofRetroMalayalam_20260901050534.jpg", n: "36" },
	] },
	{ code: "bhojpuri", label: "Bhojpuri",
	  latest: { name: "Chartbusters 2026 - Bhojpuri", url: "https://www.jiosaavn.com/featured/chartbusters-2026-bhojpuri/i-y0PrsZyz1wl9Cu-HDmVQ__", img: "https://c.saavncdn.com/editorial/Chartbusters2026Bhojpuri_20260707082759.jpg", n: "50" },
	  playlists: [
		{ name: "Pawan Singh - Sad Songs", url: "https://www.jiosaavn.com/featured/pawan-singh-sad-songs-/L,dkeWZ,iL-uS6o99JG3mQ__", img: "https://c.saavncdn.com/editorial/PawanSinghSadSongsBhojpuri_20240318050833.jpg", n: "30" },
		{ name: "Let's Play - Pawan Singh", url: "https://www.jiosaavn.com/featured/lets-play-pawan-singh/nFjJ3YhbbBA_", img: "https://c.saavncdn.com/editorial/Let_sPlayPawanSingh_20240919082740.jpg", n: "50" },
		{ name: "Viral Nation", url: "https://www.jiosaavn.com/featured/viral-nation/tfVkYjaAbZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ViralNation_20260831114743.jpg", n: "30" },
		{ name: "Shilpi Raj - Sad Songs", url: "https://www.jiosaavn.com/featured/shilpi-raj-sad-songs/NTdZcRvmtiusud-ETNX4vg__", img: "https://c.saavncdn.com/editorial/ShilpiRajSadSongs_20240328121708.jpg", n: "26" },
		{ name: "Chartbusters 2026 - Bhojpuri", url: "https://www.jiosaavn.com/featured/chartbusters-2026-bhojpuri/i-y0PrsZyz1wl9Cu-HDmVQ__", img: "https://c.saavncdn.com/editorial/Chartbusters2026Bhojpuri_20260707082759.jpg", n: "50" },
		{ name: "ArtistOne Finds", url: "https://www.jiosaavn.com/featured/artistone-finds/nOyNH0fuWtGP3AiNrzXpzA__", img: "https://c.saavncdn.com/editorial/ArtistOneFinds_20260904103023.jpg", n: "50" },
		{ name: "Best Of Dance - Bhojpuri", url: "https://www.jiosaavn.com/featured/best-of-dance-bhojpuri/O2S2vcw1ai2O0eMLZZxqsA__", img: "https://c.saavncdn.com/editorial/BestOfDanceBhojpuri_20260622112317.jpg", n: "30" },
		{ name: "Let's Play - Shilpi Raj", url: "https://www.jiosaavn.com/featured/lets-play-shilpi-raj-/Rl,Zz6Dy5vZFo9wdEAzFBA__", img: "https://c.saavncdn.com/editorial/Let_sPlayShilpiRaj_20250310063006.jpg", n: "40" },
		{ name: "Khesari Lal Yadav - Sad Songs", url: "https://www.jiosaavn.com/featured/khesari-lal-yadav-sad-songs-/smjk1WNhaWzgEhiRleA1SQ__", img: "https://c.saavncdn.com/editorial/KhesariLalYadavSadSongs_20240723095841.jpg", n: "30" },
		{ name: "Let's Play - Samar Singh", url: "https://www.jiosaavn.com/featured/lets-play-samar-singh/pVwO6SuKvNdieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/Let_sPlaySamarSingh_20241017083940.jpg", n: "50" },
	] },
	{ code: "urdu", label: "Urdu",
	  latest: { name: "Urdu Trending Hits", url: "https://www.jiosaavn.com/featured/urdu-trending-hits/N3jEdkwTL4XfemJ68FuXsA__", img: "https://c.saavncdn.com/editorial/UrduTrendingHits_20240917092910.jpg", n: "30" },
	  playlists: [
		{ name: "Khwaja Garib Nawaz", url: "https://www.jiosaavn.com/featured/khwaja-garib-nawaz/DZqMWJjhfeowkg5tVhI3fw__", img: "https://c.saavncdn.com/editorial/KhwajaGaribNawaz_20240917093031.jpg", n: "50" },
		{ name: "Urdu - Dard Bhari Ghazal", url: "https://www.jiosaavn.com/featured/urdu-dard-bhari-ghazal/jWT8Ix6ZKFl2owbrZmPKxA__", img: "https://c.saavncdn.com/editorial/UrduDardBhariGhazal_20230613100439.jpg", n: "32" },
		{ name: "Viral Nation", url: "https://www.jiosaavn.com/featured/viral-nation/tfVkYjaAbZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ViralNation_20260831114743.jpg", n: "30" },
		{ name: "Urdu - Original Version of Nusrat Fateh Ali Khan", url: "https://www.jiosaavn.com/featured/urdu-original-version-of-nusrat-fateh-ali-khan/KgCgShyBoD,l7JpGxdAPvw__", img: "https://c.saavncdn.com/editorial/UrduOriginalVersionofNusratFatehAliKhan_20230725142537.jpg", n: "25" },
		{ name: "Naate Paak", url: "https://www.jiosaavn.com/featured/naate-paak/qJJ3b1Q9AXIwkg5tVhI3fw__", img: "https://c.saavncdn.com/editorial/NaatePaak_20240917092716.jpg", n: "32" },
		{ name: "ArtistOne Finds", url: "https://www.jiosaavn.com/featured/artistone-finds/nOyNH0fuWtGP3AiNrzXpzA__", img: "https://c.saavncdn.com/editorial/ArtistOneFinds_20260904103023.jpg", n: "50" },
		{ name: "Naat Sharif - Qadri", url: "https://www.jiosaavn.com/featured/naat-sharif-qadri/3Txa,GLhSjY_", img: "https://c.saavncdn.com/editorial/NaatSharifQadri_20240905142635.jpg", n: "36" },
		{ name: "Kids Naat", url: "https://www.jiosaavn.com/featured/kids-naat/SSKXhADWG,-vZ3uUE6bUVw__", img: "https://c.saavncdn.com/editorial/UrduKidsZone2023_20230421152536.jpg", n: "81" },
		{ name: "Eid Mubarak", url: "https://www.jiosaavn.com/featured/eid-mubarak/nfnvf,rcquc_", img: "https://c.saavncdn.com/editorial/EidMubarakUrdu_20240408074449.jpg", n: "30" },
		{ name: "Salat O Salam", url: "https://www.jiosaavn.com/featured/salat-o-salam/VI9N5PDo6yHWCn-BpjaL7g__", img: "https://c.saavncdn.com/editorial/SalatOSalam_20250227123605.jpg", n: "20" },
	] },
	{ code: "haryanvi", label: "Haryanvi",
	  latest: { name: "Chartbusters 2026 - Haryanvi", url: "https://www.jiosaavn.com/featured/chartbusters-2026-haryanvi/cMmty07t9s,vz,QNANKgeg__", img: "https://c.saavncdn.com/editorial/Chartbusters2026Haryanvi_20260707091254.jpg", n: "50" },
	  playlists: [
		{ name: "Let's Play -Dhanda Nyoliwala", url: "https://www.jiosaavn.com/featured/lets-play-dhanda-nyoliwala/wu4Qnf8HM9pTHgJw1pi47A__", img: "https://c.saavncdn.com/editorial/Let_sPlayDhandaNyoliwala_20260112102009.jpg", n: "50" },
		{ name: "Let's Play - Masoom Sharma", url: "https://www.jiosaavn.com/featured/lets-play-masoom-sharma/DJgtwTfTPUnc1EngHtQQ2g__", img: "https://c.saavncdn.com/editorial/Let_sPlayMasoomSharma_20250113164258.jpg", n: "50" },
		{ name: "Viral Nation", url: "https://www.jiosaavn.com/featured/viral-nation/tfVkYjaAbZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ViralNation_20260831114743.jpg", n: "30" },
		{ name: "Let's Play - Sapna Choudhary", url: "https://www.jiosaavn.com/featured/lets-play-sapna-choudhary-/Ke5y5anwb35ieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/Let_sPlaySapnaChoudhary_20250310081552.jpg", n: "50" },
		{ name: "Dance Hits 2025 - Haryanvi", url: "https://www.jiosaavn.com/featured/dance-hits-2025-haryanvi/La32CokN5aUva8qgomsMOw__", img: "https://c.saavncdn.com/editorial/DanceHits2025Haryanvi_20260108184533.jpg", n: "20" },
		{ name: "ArtistOne Finds", url: "https://www.jiosaavn.com/featured/artistone-finds/nOyNH0fuWtGP3AiNrzXpzA__", img: "https://c.saavncdn.com/editorial/ArtistOneFinds_20260904103023.jpg", n: "50" },
		{ name: "Let's Play - Amit Saini Rohtakiya", url: "https://www.jiosaavn.com/featured/lets-play-amit-saini-rohtakiya/TP7VG7dqWhiO0eMLZZxqsA__", img: "https://c.saavncdn.com/editorial/Let_sPlayAmitSainiRohtakiya_20250123061559.jpg", n: "50" },
		{ name: "Best of Romance - Haryanvi", url: "https://www.jiosaavn.com/featured/best-of-romance-haryanvi/uRjRUlP4uzbbdh3Fl54,TQ__", img: "https://c.saavncdn.com/editorial/BestofRomanceHaryanvi_20260622113539.jpg", n: "30" },
		{ name: "Let's Play - Amanraj Gill", url: "https://www.jiosaavn.com/featured/lets-play-amanraj-gill/D1jK,vfFEbffemJ68FuXsA__", img: "https://c.saavncdn.com/editorial/Let_sPlayAmanrajGill_20250414101438.jpg", n: "30" },
		{ name: "Chartbusters 2025 - Haryanvi", url: "https://www.jiosaavn.com/featured/chartbusters-2025-haryanvi/PQpZtLAH14oC0-RsHAbZ7g__", img: "https://c.saavncdn.com/editorial/Chartbusters2025Haryanvi_20260108182527.jpg", n: "50" },
	] },
	{ code: "rajasthani", label: "Rajasthani",
	  latest: { name: "New Music Rajasthani", url: "https://www.jiosaavn.com/featured/new-music-rajasthani/MUzu3u7oadal7JpGxdAPvw__", img: "https://c.saavncdn.com/editorial/NewMusicRajasthani_20250811055158.jpg", n: "20" },
	  playlists: [
		{ name: "Most Streamed Love Songs -Rajasthani", url: "https://www.jiosaavn.com/featured/most-streamed-love-songs-rajasthani/JTmd6GT9Dr0zQXa1XvOQjA__", img: "https://c.saavncdn.com/editorial/MostStreamedLoveSongsRajasthani_20250320161832.jpg", n: "35" },
		{ name: "Let's Play - Twinkle Vaishnav", url: "https://www.jiosaavn.com/featured/lets-play-twinkle-vaishnav/bqMC2PZWSLHExeh5N5JWFg__", img: "https://c.saavncdn.com/editorial/Let_sPlayTwinkleVaishnav_20241217065641.jpg", n: "20" },
		{ name: "Viral Nation", url: "https://www.jiosaavn.com/featured/viral-nation/tfVkYjaAbZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ViralNation_20260831114743.jpg", n: "30" },
		{ name: "Let's Play - Anil Rawat", url: "https://www.jiosaavn.com/featured/lets-play-anil-rawat/OqfLBpBqAjDflAdLIHj8iA__", img: "https://c.saavncdn.com/editorial/Let_sPlayAnilRawat_20250515061752.jpg", n: "20" },
		{ name: "Let's Play - Bablu Ankiya", url: "https://www.jiosaavn.com/featured/lets-play-bablu-ankiya/oGxTbYT4NVvnZqie6EVsAw__", img: "https://c.saavncdn.com/editorial/Let_sPlayBabluAnkiya_20250320161643.jpg", n: "29" },
		{ name: "ArtistOne Finds", url: "https://www.jiosaavn.com/featured/artistone-finds/nOyNH0fuWtGP3AiNrzXpzA__", img: "https://c.saavncdn.com/editorial/ArtistOneFinds_20260904103023.jpg", n: "50" },
		{ name: "Let's Play - Prakash Mali", url: "https://www.jiosaavn.com/featured/lets-play-prakash-mali/3p4,5Pz9V8k_", img: "https://c.saavncdn.com/editorial/BhaktiPrakashMali_20240521085619.jpg", n: "26" },
		{ name: "Let's Play - Rapperiya Balam", url: "https://www.jiosaavn.com/featured/lets-play-rapperiya-balam/J3aQqJcjkLirB59Sr2unUQ__", img: "https://c.saavncdn.com/editorial/Let_sPlayRapperiyaBalamRajasthani_20250320161648.jpg", n: "20" },
		{ name: "Let's Play Geeta Goswami - Rajasthani", url: "https://www.jiosaavn.com/featured/lets-play-geeta-goswami-rajasthani/N4I9yDiMS8ZYYWvstd0eCA__", img: "https://c.saavncdn.com/editorial/GeetaGoswami_20240301122718.jpg", n: "25" },
		{ name: "Let's Play - Rani Rangili", url: "https://www.jiosaavn.com/featured/lets-play-rani-rangili/oD5bqrQAV-SPujkz47ksHQ__", img: "https://c.saavncdn.com/editorial/Let_sPlayRaniRangili_20250320161804.jpg", n: "27" },
	] },
	{ code: "odia", label: "Odia",
	  latest: { name: "Chartbusters 2026 - Odia", url: "https://www.jiosaavn.com/featured/chartbusters-2026-odia/ZI,mzcMd,pl613W6L-cCSw__", img: "https://c.saavncdn.com/editorial/Chartbusters2026Odia_20260713184227.jpg", n: "50" },
	  playlists: [
		{ name: "Chartbusters 2026 - Odia", url: "https://www.jiosaavn.com/featured/chartbusters-2026-odia/ZI,mzcMd,pl613W6L-cCSw__", img: "https://c.saavncdn.com/editorial/Chartbusters2026Odia_20260713184227.jpg", n: "50" },
		{ name: "Let's Play - Humane Sagar", url: "https://www.jiosaavn.com/featured/lets-play-humane-sagar/zfs3622ON9GO0eMLZZxqsA__", img: "https://c.saavncdn.com/editorial/Let_sPlayHumaneSagar_20240430101155.jpg", n: "50" },
		{ name: "Viral Nation", url: "https://www.jiosaavn.com/featured/viral-nation/tfVkYjaAbZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ViralNation_20260831114743.jpg", n: "30" },
		{ name: "Sambalpuri Prema", url: "https://www.jiosaavn.com/featured/sambalpuri-prema/rMd6,5EHzrp71f3QFG7QOA__", img: "https://c.saavncdn.com/editorial/SambalpuriPrema_20260727123432.jpg", n: "28" },
		{ name: "Let's Play - Bijay Anand Sahu", url: "https://www.jiosaavn.com/featured/lets-play-bijay-anand-sahu/OhEuBQnMKK0zQXa1XvOQjA__", img: "https://c.saavncdn.com/editorial/Let_sPlayBijayAnandSahu_20260810170252.jpg", n: "26" },
		{ name: "ArtistOne Finds", url: "https://www.jiosaavn.com/featured/artistone-finds/nOyNH0fuWtGP3AiNrzXpzA__", img: "https://c.saavncdn.com/editorial/ArtistOneFinds_20260904103023.jpg", n: "50" },
		{ name: "Monsoon Hits - Odia", url: "https://www.jiosaavn.com/featured/monsoon-hits-odia/tLqkA59nSDXoTK7Cft7y8w__", img: "https://c.saavncdn.com/editorial/MonsoonHitsOdia_20260812093701.jpg", n: "29" },
		{ name: "Let's Play - Krishna Beuraa - Odia", url: "https://www.jiosaavn.com/featured/lets-play-krishna-beuraa-odia/5MTCoeoBSrCN8OQeUngFdA__", img: "https://c.saavncdn.com/editorial/Let_sPlayKrishnaBeuraaOdia_20260331061519.jpg", n: "20" },
		{ name: "70s Romance - Odia", url: "https://www.jiosaavn.com/featured/70s-romance-odia/riVM5xB4SZy5MW-661Z5Dg__", img: "https://c.saavncdn.com/editorial/70sRomanceOdia_20250228141247.jpg", n: "23" },
		{ name: "Let's Play - Aseema Panda", url: "https://www.jiosaavn.com/featured/lets-play-aseema-panda-/plpBuAQEEeTfemJ68FuXsA__", img: "https://c.saavncdn.com/editorial/Let_sPlayAseemaPanda_20241018140800.jpg", n: "50" },
	] },
	{ code: "assamese", label: "Assamese",
	  latest: { name: "New Indie - Assamese", url: "https://www.jiosaavn.com/featured/new-indie-assamese-/Klzv2STl2kKPujkz47ksHQ__", img: "https://c.saavncdn.com/editorial/NewIndieAssamese_20260708154102.jpg", n: "25" },
	  playlists: [
		{ name: "Chartbusters 2026 - Assamese", url: "https://www.jiosaavn.com/featured/chartbusters-2026-assamese/gTbHuJjr3v,pJ,OEBt5Zbg__", img: "https://c.saavncdn.com/editorial/Chartbusters2026Assamese_20260713190256.jpg", n: "50" },
		{ name: "Best of Indie - Assamese", url: "https://www.jiosaavn.com/featured/best-of-indie-assamese/GEZV-npX75kV3Xpvr9dnYw__", img: "https://c.saavncdn.com/editorial/It_sIndieAssamese_20260327132439.jpg", n: "30" },
		{ name: "Viral Nation", url: "https://www.jiosaavn.com/featured/viral-nation/tfVkYjaAbZJieSJqt9HmOQ__", img: "https://c.saavncdn.com/editorial/ViralNation_20260831114743.jpg", n: "30" },
		{ name: "Let's Play - Zubeen Garg - Assamese", url: "https://www.jiosaavn.com/featured/lets-play-zubeen-garg-assamese/qHnRwjgn1XDfemJ68FuXsA__", img: "https://c.saavncdn.com/editorial/Let_sPlayZubeenGargAssamese_20240613114447.jpg", n: "50" },
		{ name: "House Party - Assamese", url: "https://www.jiosaavn.com/featured/-house-party-assamese/sm3NobDwXgnufxkxMEIbIw__", img: "https://c.saavncdn.com/editorial/HouseppartyAssamese_20251029172041.jpg", n: "37" },
		{ name: "ArtistOne Finds", url: "https://www.jiosaavn.com/featured/artistone-finds/nOyNH0fuWtGP3AiNrzXpzA__", img: "https://c.saavncdn.com/editorial/ArtistOneFinds_20260904103023.jpg", n: "50" },
		{ name: "Zubeen Garg - Party Songs", url: "https://www.jiosaavn.com/featured/zubeen-garg-party-songs/70w4cIWXiC562UBQeMeB4Q__", img: "https://c.saavncdn.com/editorial/ZubeenGargPartySongs_20251003104818.jpg", n: "20" },
		{ name: "Best of 90s - Assamese", url: "https://www.jiosaavn.com/featured/best-of-90s-assamese/wHQMAZqEbRRuOxiEGmm6lQ__", img: "https://c.saavncdn.com/editorial/Bestof90sAssamese_20250623121502.jpg", n: "41" },
		{ name: "Let's Play - Bhupen Hazarika - Assamese", url: "https://www.jiosaavn.com/featured/lets-play-bhupen-hazarika-assamese/EeO1Kpg3r4JuOxiEGmm6lQ__", img: "https://c.saavncdn.com/editorial/Let_sPlayBhupenHazarikaAssamese_20240613122440.jpg", n: "86" },
		{ name: "Chill Time - Assamese", url: "https://www.jiosaavn.com/featured/-chill-time-assamese/WqEgHIkyT,RuOxiEGmm6lQ__", img: "https://c.saavncdn.com/editorial/ChillTimeAssamese_20240808103736.jpg", n: "28" },
	] },
];
